server:
  name: "menu-api"
  addr: "127.0.0.1:18000"
zap:
  debugFileName: "d:/Code/Golang/new-data/new-data/ms_project/logs/debug/menu-debug.log"
  infoFileName: "d:/Code/Golang/new-data/new-data/ms_project/logs/info/menu-info.log"
  warnFileName: "d:/Code/Golang/new-data/new-data/ms_project/logs/error/menu-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3
etcd:
  addrs:
    - "127.0.0.1:2379"
mysql:
  username: root
  password: root
  host: 127.0.0.1
  port: 13306
  db: msproject
